default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: wham_dev

test:
  <<: *default
  database: wham_test

production:
  <<: *default
  database: wham_prod
